remove the ft_put* family of functions
These where poorly designed as they return an void instead of an int.
Most write functions return the amount of characters printed on success
and -1 on failure. These return a void making it impossible to test for
failure.

This will fix the following compile error:

../subprojects/libft/src/ft_putchar_fd.c: In function ‘ft_putchar_fd’:
../subprojects/libft/src/ft_putchar_fd.c:18:8: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
  (void)write(fd, (void *)&c, (size_t)1);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~